name: build-and-push

on:
  pull_request:
    branches: [ master ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    env:
        IMAGE: webapp0827.azurecr.io/invite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      
  
      - name: Log into ACR
        uses: docker/login-action@v1
        with:
          registry: webapp0827.azurecr.io
          username: webapp0827
          password: ${{ secrets.sasank }}

    

      - name: Build and publish container image with tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./tmpdir/Dockerfile
          tags: user/app:latest
        
        
