name: build-and-push

on:
  pull_request:
    branches: [ master ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    env:
        IMAGE: webapp0827.azurecr.io/invite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    

    - name: Generate build ID
      id: prep
      run: |
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::master-${sha}-${ts}"
    # These are prerequisites for the docker build step
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into ACR
      uses: docker/login-action@v1
      with:
        registry: webapp0827.azurecr.io
        username: webapp0827
        password: ${{ secrets.SASANK }}

    

    - name: Build and publish container image with tag
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./temdir/Dockerfile
        tags: ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
        
